//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeSites.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecipeEntities : DbContext
    {
        public RecipeEntities()
            : base("name=RecipeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLCOMMENT> TBLCOMMENT { get; set; }
        public virtual DbSet<TBLRATING> TBLRATING { get; set; }
        public virtual DbSet<TBLRECIPE> TBLRECIPE { get; set; }
        public virtual DbSet<TBLUSER> TBLUSER { get; set; }
    }
}
