//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeSites.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRECIPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLRECIPE()
        {
            this.TBLCOMMENT = new HashSet<TBLCOMMENT>();
        }
    
        public int Recipe_Id { get; set; }
        public string Title { get; set; }
        public string Integredients { get; set; }
        public string Instructions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCOMMENT> TBLCOMMENT { get; set; }
    }
}
